services:
    train:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: train-model-generic
        volumes:
            - .:/app
        entrypoint: python src/pipeline/train_pipeline.py
        environment:
            - ENV=production
            - PYTHONPATH=/app