services:
    train:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: train-model-generic
        volumes:
            - .:/app
        entrypoint: python src/pipeline/train_pipeline.py
        environment:
            - ENV=production
            - PYTHONPATH=/app
            
    predict:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: predict-model-generic
        volumes:
            - .:/app
        entrypoint: python app.py
        ports:
            - '5000:5000'
        environment:
            - ENV=production
            - PYTHONPATH=/app
